# Generated by Django 5.0.4 on 2024-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_last_seen_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='last_seen',
            new_name='seen',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.FileField(blank=True, upload_to='chat/documents'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to='chat/images'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
